package pl.grm.narutocraftmod.Libs.registry;

import net.minecraft.item.Item;
import cpw.mods.fml.common.registry.GameRegistry;

import pl.grm.narutocraftmod.jutsu.AsaKujaku;
import pl.grm.narutocraftmod.jutsu.Byakugo;
import pl.grm.narutocraftmod.jutsu.ChakuraNoMesu;
import pl.grm.narutocraftmod.jutsu.Dokugiri;
import pl.grm.narutocraftmod.jutsu.Enmakugire;
import pl.grm.narutocraftmod.jutsu.FukimiHari;
import pl.grm.narutocraftmod.jutsu.FumaNinken;
import pl.grm.narutocraftmod.jutsu.Hadan;
import pl.grm.narutocraftmod.jutsu.HariJizo;
import pl.grm.narutocraftmod.jutsu.Haykkaroran;
import pl.grm.narutocraftmod.jutsu.Hirudora;
import pl.grm.narutocraftmod.jutsu.Iaido;
import pl.grm.narutocraftmod.jutsu.InyuShometsu;
import pl.grm.narutocraftmod.jutsu.Issen;
import pl.grm.narutocraftmod.jutsu.JikukanKekkai;
import pl.grm.narutocraftmod.jutsu.KageBuyo;
import pl.grm.narutocraftmod.jutsu.Kai;
import pl.grm.narutocraftmod.jutsu.KawarimiNoJutsu;
import pl.grm.narutocraftmod.jutsu.KokuangyoNoJutsu;
import pl.grm.narutocraftmod.jutsu.KosaHo;
import pl.grm.narutocraftmod.jutsu.Koukongarasu;
import pl.grm.narutocraftmod.jutsu.KuchiyoseRashomon;
import pl.grm.narutocraftmod.jutsu.Meisaigakure;
import pl.grm.narutocraftmod.jutsu.MikazukiKiri;
import pl.grm.narutocraftmod.jutsu.NanKaizou;
import pl.grm.narutocraftmod.jutsu.NawanukeNoJutsu;
import pl.grm.narutocraftmod.jutsu.OmoteRenge;
import pl.grm.narutocraftmod.jutsu.Omotegiri;
import pl.grm.narutocraftmod.jutsu.RaigenRaikochu;
import pl.grm.narutocraftmod.jutsu.Ranshinsho;
import pl.grm.narutocraftmod.jutsu.Rasengan;
import pl.grm.narutocraftmod.jutsu.Rasengan2;
import pl.grm.narutocraftmod.jutsu.Rasengan3;
import pl.grm.narutocraftmod.jutsu.SaikanChushutsuNoJutsu;
import pl.grm.narutocraftmod.jutsu.SamuraiSabreTechnique;
import pl.grm.narutocraftmod.jutsu.Sharingan;
import pl.grm.narutocraftmod.jutsu.ShunshinNoJutsu;
import pl.grm.narutocraftmod.jutsu.UraRenge;
import pl.grm.narutocraftmod.jutsu.Yosakugiri;

public class RegJutsus {
	private static int id = 4600;
	public static Item KNoJutsu = new KawarimiNoJutsu(id);
    public static Item SNoJutsu = new ShunshinNoJutsu(id+1);
   	public static Item Sharingan = new Sharingan(id+2);
   	public static Item Rasengan = new Rasengan(id+3);
   	public static Item Rasengan2 = new Rasengan2(id+4);
   	public static Item Rasengan3 = new Rasengan3(id+5);
   	public static Item AsaKujaku = new AsaKujaku(id+6);
   	public static Item Byakugo = new Byakugo(id+7);
   	public static Item ChakuraNoMesu = new ChakuraNoMesu(id+8);
   	public static Item Dokugiri = new Dokugiri(id+9);
   	public static Item Enmakugire = new Enmakugire(id+10);
   	public static Item FukimiHari = new FukimiHari(id+11);
   	public static Item FumaNinken = new FumaNinken(id+12);
   	public static Item Hadan = new Hadan(id+13);
   	public static Item HariJizo = new HariJizo(id+14);
   	public static Item Haykkaroran = new Haykkaroran(id+15);
   	public static Item Hirudora = new Hirudora(id+15);
   	public static Item Iaido = new Iaido(id+16);
   	public static Item InyuShometsu = new InyuShometsu(id+17);
   	public static Item Issen = new Issen(id+18);
   	public static Item JikukanKekkai = new JikukanKekkai(id+19);
   	public static Item KageBuyo = new KageBuyo(id+20);
   	public static Item Kai = new Kai(+21);
   	public static Item KokuangyoNoJutsu = new KokuangyoNoJutsu(id+22);
   	public static Item KosaHo = new KosaHo(id+23);
   	public static Item Koukongarasu = new Koukongarasu(id+24);
   	public static Item KuchiyoseRashomon = new KuchiyoseRashomon(id+25);
   	public static Item Meisaigakure = new Meisaigakure(id+26);
   	public static Item MikazukiKiri = new MikazukiKiri(id+27);
   	public static Item NanKaizou = new NanKaizou(id+28);
   	public static Item NawanukeNoJutsu = new NawanukeNoJutsu(id+29);
   	public static Item Omotegiri = new Omotegiri(id+30);
   	public static Item OmoteRenge = new OmoteRenge(id+31);
   	public static Item RaigenRaikochu = new RaigenRaikochu(id+32);
   	public static Item Ranshinsho = new Ranshinsho(id+33);
   	public static Item SaikanChushutsuNoJutsu = new SaikanChushutsuNoJutsu(id+34);
   	public static Item SamuraiSabreTechnique = new SamuraiSabreTechnique(id+35);
   	public static Item UraRenge = new UraRenge(id+36);
   	public static Item Yosakugiri = new Yosakugiri(id+3);
   	
   	 
   	
//	public static Item  = new (id+);
   	
   	
   	public static void RegPowersList() {
		GameRegistry.registerItem(KNoJutsu, "KawarimiNoJutsu");
		GameRegistry.registerItem(SNoJutsu, "ShunshinNoJutsu");
		GameRegistry.registerItem(Sharingan, "Sharingan");
		GameRegistry.registerItem(Rasengan, "Rasengan");
		GameRegistry.registerItem(Rasengan2, "OdamaRasengan");
		GameRegistry.registerItem(Rasengan3, "ChioOdamaRasengan");
		GameRegistry.registerItem(AsaKujaku, "Asa Kujaku");
		GameRegistry.registerItem(Byakugo, "Byakugo");
		GameRegistry.registerItem(ChakuraNoMesu, "Chakura No Mesu");
		GameRegistry.registerItem(Dokugiri, "Dokugiri");
		GameRegistry.registerItem(Enmakugire, "Enmakugire");
		GameRegistry.registerItem(FukimiHari, "FukimiHari");
		GameRegistry.registerItem(FumaNinken, "Fuma Ninken");
		GameRegistry.registerItem(Hadan, "Hadan");
		GameRegistry.registerItem(HariJizo, "HariJizo");
		GameRegistry.registerItem(Haykkaroran, "Haykkaroran");
		GameRegistry.registerItem(Hirudora, "Hirudora");
		GameRegistry.registerItem(Iaido, "Iaido");
		GameRegistry.registerItem(InyuShometsu, "InyuShometsu");
		GameRegistry.registerItem(Issen, "Issen");
		GameRegistry.registerItem(JikukanKekkai, "Jikukan Kekkai");
		GameRegistry.registerItem(KageBuyo, "Kage Buyo");
		GameRegistry.registerItem(Kai, "Kai");
		GameRegistry.registerItem(KokuangyoNoJutsu, "KokouangyoNo Jutsu");
		GameRegistry.registerItem(KosaHo, "KosaHo");
		GameRegistry.registerItem(Koukongarasu, "Koukongarasu");
		GameRegistry.registerItem(KuchiyoseRashomon, "KuchiyoseRashomon");
		GameRegistry.registerItem(Meisaigakure, "Meisaigakure");
		GameRegistry.registerItem(MikazukiKiri, "Mikazuki Kiri");
		GameRegistry.registerItem(NanKaizou, "Nan Kaizou");
		GameRegistry.registerItem(NawanukeNoJutsu, "Nawanuke No Jutsu");
		GameRegistry.registerItem(Omotegiri, "Omotegiri");
		GameRegistry.registerItem(OmoteRenge, "Omote Renge");
		GameRegistry.registerItem(RaigenRaikochu, "RaigenRaikochi");
		GameRegistry.registerItem(Ranshinsho, "Ranshinsho");
		GameRegistry.registerItem(SaikanChushutsuNoJutsu, "Saikan Chushutsu No Jutsu");
		GameRegistry.registerItem(SamuraiSabreTechnique, "SamuraiSabreTehcnique");
		GameRegistry.registerItem(UraRenge, "Ura Renge");
		GameRegistry.registerItem(Yosakugiri, "Yosakugiri");
		//GameRegistry.registerItem(, "");
   	}
}
